extends Node2D

var i = 0
var bubble_text = ["In the arctic, the natives are complaining about the disappearing populations of whales. 
You locate the source of the issue to be nearby boats, being too loud for whales to hunt and communicate in the area. 
With the help of a newly passed local law, it is now your job to reroute the propellers and sonar equipment 
of the boats to reduce the noise generated by them, to get the whale to come back to the area.",
"-The noise generated by boats can scare the animals that get too close to the source, 
causing them to panic and rise to the surface too quickly, which can cause decompression sickness, 
which has side effects of tissue damage from the gas bubble lesions.

-Unnatural noises caused by sonar equipment and propellers can cause nearby animals to move away from
 the sounds, causing them to change their natural habits to accommodate for the noisy times of day, 
sometimes increasing their anti-predatory behavior.

-Noise Pollution can interfere with the detection of acoustic signals of various animals that utilize this habit 
to hunt or communicate with each other, such as dolphins or whales. 
This can lead to changes in individual and social behavior, changed metabolism, and hampered population 
recruitment, affecting the health and service of marine ecosystems.",
"Connect each node to the corresponding color and shape, 
without overlapping wires."]
var bubble_text_length = bubble_text[i].length()
var current_text = ""
@onready var label = get_node("VBoxContainer/Label")
@onready var ninerect = get_node("VBoxContainer/Label/NinePatchRect")

func _ready():
	current_text += bubble_text[i]
	label.text = current_text

func _on_button_pressed():
	i += 1
	current_text = ""
	current_text += bubble_text[i]
	label.text = current_text
