extends Node2D

var i = 0
var bubble_text = ["In the arctic, the natives are complaining about the disappearing populations of whales. You locate the source of the issue to be nearby boats being too loud for whales to hunt and communicate in the area. With the help of a newly passed local law, it is now your job to reroute the path the boats take everyday, and avoid the hunting areas of the whales.",
"-Noise generated by boats can cause nearby fish to panic and rise upwards too fast, causing the fish to get sick and possibly die 

-Noise from sonar equipment and propellers can cause animals to swim away, changing their natural habits to avoid the unnatural sound.

-The acoustic signals of animals such as dolphins can be interfered with by noise pollution, which can change the hunting and eating habits of nearby ecosystems.",
"Create a path between each matching ship, without overlapping each other to avoid crashing. Do not make a path through the whales, to avoid conflict with their hunting patterns.",
"alright it should start now"]
var bubble_text_length = bubble_text[i].length()
var current_text = ""
@onready var label = get_node("MarginContainer/VBoxContainer/Label")

func _ready():
	current_text += bubble_text[i]
	label.text = current_text



func _on_button_pressed():
	i += 1
	current_text = ""
	current_text += bubble_text[i]
	label.text = current_text
	if i == 3:
		SceneTransition.change_scene("res://grid.tscn")


	pass # Replace with function body.
